---
title: "Twitter"
author: "Sasha"
date: "21 de junio 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rtweet)

library(dplyr)
```

## rtweet 

```{r}
my_filename <- "./data/twitter_sample_alberto.rds"

if(!file.exists(my_filename)){
  rt <- search_tweets(
    "alberto", n = 18000, include_rts = FALSE
  )
  readr::write_rds(rt, my_filename )
} else {
  rt <- readr::read_rds( my_filename )
}
```



## Filtrar por "location"

En general no es buena idea ya que depende del campo "location" que ponga el usuario.

```{r}
de_argentina <- 
  str_detect(rt$location,"argentina")|
  str_detect(rt$location,"Argentina")

sum(de_argentina)

argentina_tweets <- rt %>% 
  filter(de_argentina)
```

```{r}
  argentina_tweets$text %>% 
  head()
```

## Mirar con tidytext

```{r}
library(tidytext)

argentina_tweets %>% 
  unnest_tokens(word,text) %>% 
  group_by(word) %>% 
  count(word,sort=TRUE) %>% 
  head(100)
```

## Mirar las fechas

```{r}
argentina_tweets <- argentina_tweets %>% 
  mutate(Fecha = as.Date(created_at))
```

```{r}
argentina_tweets %>% 
  group_by(Fecha) %>% 
  count(sort=TRUE)
```
No particularmente interesante, pero demuestra la técnica.


```{r}
filename_2 <- "./data/twitter_biden.rds"
if(!file.exists(filename_2)){
  rt2 <- search_tweets("Biden", n=18000, include_rts = FALSE)
  readr::write_rds(rt2, filename_2)
} else {
  rt2 <- readr::read_rds(filename_2)
}
```

```{r}
rt2$text %>% 
  head()
```

```{r}
rt2 %>% 
  unnest_tokens(word,text) %>% 
  group_by(word) %>% 
  count(sort = TRUE)
```

```{r}
library(stringr)
estan_juntos <- rt2 %>% 
  filter(str_detect(text,"Trump")) %>% 
  filter(str_detect(text,"Biden"))
```

```{r}
nrow(estan_juntos)
```

```{r}
estan_juntos$text[1:10]
```

```{r}
estan_juntos <- rt2 %>% 
  filter(str_detect(text,"Trump") & #and
           str_detect(text,"Biden")
         )
```

```{r}
no_estan_juntos_necesariamente <- rt2 %>% 
  filter(str_detect(text,"Trump") | #or
           str_detect(text,"Rise"))
```

```{r}
ejemplo2 <- rt2 %>% 
  filter(str_detect(text,"Trump")) %>% 
  filter(
    str_detect(text,"southern") | 
      str_detect(text,"northern") | 
      str_detect(text,"western") 
  )
```

```{r}
nrow(ejemplo2)
```
```{r}
ejemplo2$text
```

