---
title: "¿Quién gana más?"
author: "Aleksander Dietrichson, PhD"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fuente de los datos

INDEC: 

https://www.indec.gob.ar/indec/web/Institucional-Indec-BasesDeDatos

Manual:
https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_registro_4T2020.pdf

* PP08D1 = Sueldo
* CH04 N = Sexo **codigos**:1 = varón, 2 = mujer

## Leer los datos

```{r}
my_data <- read.csv("./data/usu_individual_T420.txt", sep = ";" )
```


```{r}
nrow(my_data)
```

```{r}
ncol(my_data)
```



```{r}
library(dplyr)
my_data <- my_data %>%
  select(PP08D1,CH04 ) %>%
  rename("ingreso" = PP08D1) %>%
  rename("sexo" = CH04)
# "1" == "uno"
my_data$sexo <- factor(my_data$sexo, labels = c("1"="varón", "2"="mujer"))
# my_data
my_data <- my_data %>% 
  filter(!is.na(ingreso))
# my_data
```

```{r}
my_data %>% 
  group_by(sexo) %>% 
  summarize(
    Promedio = mean(ingreso),
    Mediano = median(ingreso)
  )
```



```{r}

datos_mujer <- my_data %>% 
  filter(sexo == "mujer")
datos_hombre <- my_data %>% 
  filter(sexo == "varón")

```


$\alpha$ = .05

```{r}
t.test(datos_mujer$ingreso, datos_hombre$ingreso)
```


```{r}
x = 1 #asignacion
x <- 1 #lo mismo
x == 2 #comparacion
x == 1 #comparacion
```

```{r}
options(scipen = 999)
t.test(datos_hombre$ingreso, datos_mujer$ingreso)
```

